version: '3'

services:
    python:
        build: .
        volumes:
            - /mnt/posio:/posio
        environment:
            - POSIO_SETTINGS=/app/config.py
        ports:
            - 8080:5000
